"""add ledger entries table

Revision ID: 956d6f9d7ad4
Revises: 21af9b11e5aa
Create Date: 2026-07-29 19:10:52.918093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '956d6f9d7ad4'
down_revision: Union[str, Sequence[str], None] = '21af9b11e5aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.Enum('DEBIT', 'CREDIT', name='ledgerentrytype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_ledger_amount_positive'),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transfer_id', 'wallet_id', 'entry_type', name='uq_transfer_wallet_entry_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ledger_entries')
    # ### end Alembic commands ###
