"""add funding support to ledger

Revision ID: f3303822ed47
Revises: 228a75b74b50
Create Date: 2026-09-21 22:38:40.736619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f3303822ed47"
down_revision: Union[str, Sequence[str], None] = "228a75b74b50"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "fundings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("funding_id", sa.Uuid(), nullable=False),
        sa.Column("wallet_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["wallet_id"], ["wallets.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("funding_id"),
    )

    op.add_column(
        "ledger_entries",
        sa.Column("funding_id", sa.Integer(), nullable=True),
    )

    op.alter_column(
        "ledger_entries",
        "transfer_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )

    op.create_foreign_key(
        None,
        "ledger_entries",
        "fundings",
        ["funding_id"],
        ["id"],
    )

    op.create_check_constraint(
        "ck_ledger_entry_transfer_or_funding",
        "ledger_entries",
        "(transfer_id IS NOT NULL) <> (funding_id IS NOT NULL)",
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(
        "ck_ledger_entry_transfer_or_funding",
        "ledger_entries",
        type_="check",
    )

    op.drop_constraint(
        None,
        "ledger_entries",
        type_="foreignkey",
    )

    op.alter_column(
        "ledger_entries",
        "transfer_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )

    op.drop_column(
        "ledger_entries",
        "funding_id",
    )

    op.drop_table(
        "fundings",
    )

    # ### end Alembic commands ###